### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by HuangAdam** [Fexcraft/FCL#6]
FCL translation:
[zh_cn.txt](https://github.com/Fexcraft/FCL/files/10070833/zh_cn.txt)

FVTM translation:
[zh_cn.txt](https://github.com/Fexcraft/FCL/files/10070836/zh_cn.txt)

Can not sure all translations are correct

**Comment by Fexcraft** [comment]
As long it does not cause large misunderstandings, it should be ok.
