### ISSUE TITLE
I get this error when i try to execute the better than wolves installer.

### ISSUE THREAD

**Issue by LeRandom3676** [Fexcraft/FCL#7]
Everytime i try to execute the better than wolves installer, the jar executor crashes and say nothing about it on the crash reason. But there is the log if someone can find a solution.

==================== Basic Information ====================
FCL Version: 1.1.2
Architecture: arm
Android SDK: 27
Java Version: 8
Renderer: Holy-GL4ES
Summarize: JVM launch failed, exit code = 1
==================== Basic Information ====================

invoke redirectStdio
invoke setLogPipeReady
[FCL Internal] D:/Projects/FCL/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_loader.c:77
Log pipe ready.

invoke setFCLBridge
start Android AWT Renderer thread
invoke setEventPipe
==================== Start Jar Executor ====================
[FCL Internal] D:/Projects/FCL/FoldCraftLauncher/FCLauncher/src/main/jni/fcl/fcl_event.c:193
Succeeded to set event pipe

Device: Moto G (5S) Plus
Architecture: arm
CPU:qcom
==================== Env Map ====================
Env: LIBGL_NOINTOVLHACK=1
Env: JAVA_HOME=/data/user/0/com.tungsten.fcl/app_runtime/java/jre8
Env: LIBGL_NAME=libgl4es_114.so
Env: LIBGL_STRING=Holy-GL4ES
Env: LIBGL_MIPMAP=3
Env: TMPDIR=/data/user/0/com.tungsten.fcl/cache
Env: LIBGL_ES=2
Env: LIBEGL_NAME=libEGL.so
Env: FCL_NATIVEDIR=/data/app/com.tungsten.fcl-Vp7LAAjn2_mjGNY4BsHBnQ==/lib/arm
Env: LIBGL_NOERROR=1
Env: LIBGL_VSYNC=1
Env: HOME=/storage/emulated/0/FCL/log
Env: LIBGL_NORMALIZE=1
==================== Env Map ====================
Working directory: /storage/emulated/0/FCL/.minecraft
==================== Jar Executor Arguments ====================
Jar Executor argument: /data/user/0/com.tungsten.fcl/app_runtime/java/jre8/bin/java
Jar Executor argument: -Djava.awt.headless=false
Jar Executor argument: -Dcacio.managed.screensize=1280x720
Jar Executor argument: -Dcacio.font.fontmanager=sun.awt.X11FontManager
Jar Executor argument: -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler
Jar Executor argument: -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
Jar Executor argument: -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit
Jar Executor argument: -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment
Jar Executor argument: -Xbootclasspath/p:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo/ResConfHack.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/data/user/0/com.tungsten.fcl/app_runtime/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
Jar Executor argument: -Xms768m
Jar Executor argument: -Xmx768m
Jar Executor argument: -Duser.home=/storage/emulated/0/FCL
Jar Executor argument: -Djava.io.tmpdir=/data/user/0/com.tungsten.fcl/cache/fclauncher
Jar Executor argument: -Dorg.lwjgl.opengl.libname=libgl4es_114.so
Jar Executor argument: -jar
Jar Executor argument: /storage/emulated/0/Download/cursed-fabric-btw-installer-1.1.6.jar
Hook exit success
Error occurred during initialization of VM

Could not reserve enough space for 786432KB object heap

OpenJDK exited with code : 1

**Comment by Fexcraft** [comment]
I think you are on the wrong project.
FCL here is "Fexcraft Common Library", a Mod, not a Launcher.

**Comment by Fexcraft** [comment]
Maybe it's this https://github.com/FCL-Team/FoldCraftLauncher ?

**Comment by LeRandom3676** [comment]
I'm sorry for the mistake.
